[build]
  command = "node generate.js && node minify.js && SITE_URL=$DEPLOY_PRIME_URL node sitemap.js"
  publish = "."
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
