[build]
  command = "npm run build"
  publish = "dist"

# Optional: redirect apex to www (uncomment if you choose www as primary)
# [[redirects]]
#   from = "https://yourdomain.com/*"
#   to = "https://www.yourdomain.com/:splat"
#   status = 301
#   force = true
